jobs:
  include:
    - name: "flake8"
      language: python
      python: 2.7
      install:
        - pip install flake8 pep8-naming flake8-blind-except flake8-string-format flake8-builtin flake8-commas flake8-quotes flake8-print flake8-docstrings
      script: flake8
